/**
 * Synonym table: anything a visitor might type → a mood id in the lexicon.
 *
 * Covers inflections (happiness → happy), colloquialisms (stoked → elated),
 * spelling variants (grey/gray), and concrete nouns that read as a mood
 * (thunderstorm → ominous). The resolver also stems and fuzzy-matches, so this
 * table only needs the jumps an algorithm cannot make on its own.
 */
// prettier-ignore
export const ALIASES = Object.freeze({
  // stillness
  chill: 'calm', chilled: 'calm', chilling: 'calm', chillout: 'calm', calmness: 'calm',
  calming: 'calm', unwind: 'calm', unwinding: 'calm', relax: 'calm', relaxed: 'calm',
  relaxing: 'calm', relaxation: 'calm', ease: 'calm', easygoing: 'calm', mellow: 'calm',
  placid: 'calm', soothing: 'calm', soothe: 'calm', breathe: 'calm', breathing: 'calm',
  serenity: 'serene', tranquility: 'tranquil', tranquillity: 'tranquil', peace: 'peaceful',
  peacefulness: 'peaceful', quietude: 'quiet', silence: 'still', silent: 'still', hush: 'quiet',
  stillness: 'still', mindful: 'meditative', mindfulness: 'meditative', meditation: 'meditative',
  meditate: 'meditative', yoga: 'meditative', centred: 'grounded', centered: 'grounded',
  rooted: 'grounded', steady: 'grounded', harmony: 'balanced', harmonious: 'balanced',
  equilibrium: 'balanced', rest: 'restful', resting: 'restful', repose: 'restful',
  softness: 'soft', gentleness: 'gentle', delicate: 'gentle', gentler: 'gentle',

  // joy
  joy: 'joyful', joyous: 'joyful', happiness: 'happy', glad: 'happy', gladness: 'happy',
  content: 'happy', contented: 'happy', pleased: 'happy', smile: 'happy', smiling: 'happy',
  laugh: 'cheerful', laughing: 'cheerful', laughter: 'cheerful', chipper: 'cheerful',
  merry: 'cheerful', bright: 'cheerful', brightness: 'sunny', upbeat: 'cheerful',
  thrilled: 'elated', overjoyed: 'elated', stoked: 'elated', hyped: 'euphoric', bliss: 'euphoric',
  blissful: 'euphoric', rapture: 'ecstatic', ecstasy: 'ecstatic', exhilarated: 'ecstatic',
  celebration: 'jubilant', celebrate: 'jubilant', party: 'festive', holiday: 'festive',
  christmas: 'festive', carnival: 'festive', fun: 'playful', silly: 'playful', goofy: 'playful',
  mischievous: 'playful', giggly: 'giddy', bubbly: 'giddy', glowing: 'radiant',
  luminous: 'radiant', sunshine: 'sunny', sunlight: 'sunny', sunlit: 'sunny', daylight: 'sunny',
  light: 'airy', weightless: 'buoyant', floaty: 'buoyant',

  // sorrow
  sadness: 'sad', unhappy: 'sad', down: 'sad', downcast: 'sad', blues: 'melancholy',
  gloom: 'melancholy', gloomy: 'melancholy', melancholic: 'melancholy', melancholia: 'melancholy',
  dejected: 'sad', despondent: 'sorrowful', grief: 'mournful', grieving: 'mournful',
  mourning: 'mournful', loss: 'mournful', bereaved: 'mournful', despair: 'sorrowful',
  hopeless: 'sorrowful', anguish: 'sorrowful', sorrow: 'sorrowful', crying: 'sorrowful',
  tears: 'sorrowful', weeping: 'sorrowful', heartbreak: 'heartbroken', broken: 'heartbroken',
  heartache: 'heartbroken', regret: 'wistful', wistfulness: 'wistful', rain: 'melancholy',
  rainy: 'melancholy', drizzle: 'melancholy', overcast: 'somber', sombre: 'somber',
  grave: 'somber', bleak: 'desolate', navy: 'blue', indigo: 'blue', cobalt: 'blue', azure: 'blue',

  // love
  love: 'romantic', loving: 'romantic', romance: 'romantic', valentine: 'romantic',
  crush: 'romantic', date: 'romantic', wedding: 'devoted', anniversary: 'devoted',
  loyalty: 'devoted', fondness: 'affectionate', warmhearted: 'affectionate',
  caring: 'affectionate', kindness: 'tender', softhearted: 'tender', desire: 'sensual',
  lust: 'sensual', seductive: 'sensual', sultry: 'sensual', ardent: 'passionate',
  fervent: 'passionate', yearn: 'yearning', pining: 'longing', nostalgia: 'nostalgic',
  homesick: 'longing', missing: 'longing',

  // drive
  energy: 'energetic', energised: 'energetic', energized: 'energetic', active: 'energetic',
  lively: 'energetic', spirited: 'energetic', buzzing: 'electric', charged: 'electric',
  voltage: 'electric', colourful: 'vibrant', colorful: 'vibrant', saturated: 'vibrant',
  punchy: 'vibrant', movement: 'dynamic', motion: 'kinetic', speed: 'kinetic', fast: 'kinetic',
  running: 'dynamic', sport: 'dynamic', sports: 'dynamic', workout: 'driven', gym: 'driven',
  training: 'driven', hustle: 'driven', ambition: 'aspirational', ambitious: 'aspirational',
  strong: 'bold', powerful: 'bold', power: 'bold', intense: 'fierce', ferocious: 'fierce',
  savage: 'fierce', wild: 'fierce', adventure: 'adventurous', explore: 'exploratory',
  exploring: 'exploratory', quest: 'adventurous', journey: 'wanderlust', travel: 'wanderlust',
  travelling: 'wanderlust', traveling: 'wanderlust', roadtrip: 'wanderlust', brave: 'daring',
  bravery: 'daring', courage: 'daring', courageous: 'daring', fearless: 'daring',
  reckless: 'daring', antsy: 'restless', fidgety: 'restless', hectic: 'frenetic',
  manic: 'frenetic', frantic: 'frenetic', mayhem: 'chaotic', chaos: 'chaotic', mess: 'chaotic',
  messy: 'chaotic',

  // dream
  dream: 'dreamy', dreaming: 'dreamy', dreamlike: 'dreamy', daydream: 'dreamy', pastel: 'dreamy',
  heavenly: 'ethereal', angelic: 'ethereal', gossamer: 'ethereal', weird: 'surreal',
  strange: 'surreal', bizarre: 'surreal', uncanny: 'surreal', dreamscape: 'surreal',
  fantasy: 'whimsical', fairytale: 'whimsical', storybook: 'whimsical', quirky: 'whimsical',
  magic: 'mystical', magical: 'mystical', occult: 'mystical', spiritual: 'mystical',
  witchy: 'mystical', mystic: 'mystical', fae: 'enchanted', fairy: 'enchanted',
  enchanting: 'enchanted', alien: 'otherworldly', extraterrestrial: 'otherworldly', misty: 'hazy',
  mist: 'hazy', fog: 'hazy', foggy: 'hazy', smoky: 'hazy', blurry: 'hazy', stars: 'celestial',
  star: 'celestial', starry: 'celestial', moon: 'celestial', night: 'celestial',
  nightsky: 'celestial', astral: 'cosmic', galaxy: 'cosmic', space: 'cosmic', universe: 'cosmic',
  nebula: 'cosmic',

  // focus
  focus: 'focused', concentrate: 'focused', concentration: 'focused', concentrating: 'focused',
  productive: 'focused', productivity: 'focused', deepwork: 'focused', work: 'focused',
  working: 'focused', discipline: 'disciplined', routine: 'methodical', systematic: 'methodical',
  organised: 'methodical', organized: 'methodical', tidy: 'methodical', precise: 'meticulous',
  precision: 'meticulous', detailed: 'meticulous', craft: 'meticulous',
  craftsmanship: 'meticulous', study: 'studious', studying: 'studious', school: 'studious',
  university: 'studious', exam: 'studious', revision: 'studious', reading: 'studious',
  books: 'studious', library: 'studious', logic: 'analytical', logical: 'analytical',
  rational: 'analytical', science: 'analytical', data: 'analytical', math: 'analytical',
  maths: 'analytical', thinking: 'analytical', resolve: 'resolute', persistence: 'determined',
  persistent: 'determined', grit: 'determined', motivated: 'driven', motivation: 'driven',

  // comfort
  comfy: 'cozy', comfort: 'cozy', comforting: 'cozy', cosy: 'cozy', homely: 'cozy', homey: 'cozy',
  home: 'cozy', blanket: 'cozy', fireplace: 'cozy', coffee: 'cozy', tea: 'cozy', candle: 'hygge',
  candles: 'hygge', cabin: 'hygge', farmhouse: 'rustic', countryside: 'pastoral',
  country: 'pastoral', village: 'pastoral', farm: 'pastoral', meadow: 'pastoral',
  memory: 'nostalgic', memories: 'nostalgic', childhood: 'nostalgic', throwback: 'nostalgic',
  reminiscing: 'nostalgic', remember: 'nostalgic', remembering: 'nostalgic',
  sentiment: 'sentimental', gratitude: 'grateful', thankful: 'grateful', thanks: 'grateful',
  thanksgiving: 'grateful', blessed: 'grateful', appreciation: 'grateful', appreciate: 'grateful',
  humble: 'reverent', sacred: 'reverent', holy: 'reverent', prayer: 'reverent',
  worship: 'reverent', church: 'reverent', temple: 'reverent', awe: 'awed', wonder: 'awed',
  wonderous: 'awed', wondrous: 'awed', breathtaking: 'awed', sublime: 'awed',

  // unease
  anxiety: 'anxious', anxiousness: 'anxious', worry: 'anxious', worried: 'anxious',
  worrying: 'anxious', panic: 'overwhelmed', dread: 'apprehensive', fear: 'apprehensive',
  afraid: 'apprehensive', scared: 'apprehensive', frightened: 'apprehensive', jittery: 'nervous',
  nerves: 'nervous', stress: 'tense', stressed: 'tense', stressful: 'tense', pressure: 'tense',
  strain: 'tense', unsettled: 'uneasy', awkward: 'uneasy', burnout: 'overwhelmed',
  burntout: 'overwhelmed', swamped: 'overwhelmed', busy: 'overwhelmed',

  // fire
  anger: 'angry', mad: 'angry', annoyed: 'angry', irritated: 'angry', frustrated: 'angry',
  frustration: 'angry', rage: 'furious', raging: 'furious', livid: 'furious', enraged: 'furious',
  fire: 'fiery', flames: 'fiery', burning: 'fiery', volcanic: 'fiery', protest: 'defiant',
  resistance: 'defiant', revolution: 'rebellious', rebel: 'rebellious', punk: 'rebellious',
  grunge: 'rebellious', outraged: 'indignant', outrage: 'indignant', injustice: 'indignant',

  // hope
  hope: 'hopeful', hoping: 'hopeful', optimism: 'optimistic', positive: 'optimistic',
  positivity: 'optimistic', inspiring: 'uplifting', encouraging: 'uplifting', uplift: 'uplifting',
  sunrise: 'hopeful', dawn: 'hopeful', newbeginning: 'renewed', rebirth: 'renewed',
  renewal: 'renewed', restart: 'renewed', growth: 'renewed', spring: 'vernal',
  luck: 'serendipitous', lucky: 'serendipitous', chance: 'serendipitous', fate: 'serendipitous',

  // solitude
  alone: 'lonely', loneliness: 'lonely', solitude: 'solitary', solo: 'solitary',
  hermit: 'secluded', isolation: 'isolated', remote: 'isolated', abandoned: 'desolate',
  empty: 'desolate', emptiness: 'desolate', barren: 'desolate', ruins: 'desolate',
  hidden: 'secluded', private: 'secluded', retreat: 'secluded', reflection: 'introspective',
  reflective: 'introspective', journaling: 'introspective', therapy: 'introspective',
  contemplative: 'introspective', pensive: 'introspective',

  // depletion
  tiredness: 'tired', sleepy: 'drowsy', sleep: 'drowsy', sleeping: 'drowsy', nap: 'drowsy',
  bed: 'drowsy', bedtime: 'drowsy', exhausted: 'drained', exhaustion: 'drained', fatigue: 'weary',
  fatigued: 'weary', spent: 'drained', depleted: 'drained', worndown: 'weary', wornout: 'weary',
  sluggish: 'lethargic', lazy: 'languid', laziness: 'languid', slow: 'languid',
  lounging: 'languid', idle: 'languid',

  // poise
  confidence: 'confident', selfassured: 'confident', assured: 'confident', swagger: 'confident',
  cool: 'confident', empowerment: 'empowered', strength: 'empowered', pride: 'empowered',
  proud: 'empowered', grace: 'poised', graceful: 'poised', composed: 'poised', royal: 'regal',
  royalty: 'regal', king: 'regal', queen: 'regal', crown: 'regal', noble: 'regal',
  grand: 'majestic', grandeur: 'majestic', epic: 'majestic', monumental: 'majestic',
  victory: 'triumphant', winning: 'triumphant', success: 'triumphant', achievement: 'triumphant',
  accomplished: 'triumphant',

  // making
  inspiration: 'inspired', muse: 'inspired', creativity: 'creative', create: 'creative',
  creating: 'creative', making: 'creative', maker: 'creative', art: 'creative', artist: 'creative',
  artistic: 'creative', design: 'creative', designing: 'creative', paint: 'expressive',
  painting: 'expressive', drawing: 'creative', imagination: 'imaginative', imagine: 'imaginative',
  invention: 'experimental', experiment: 'experimental', prototype: 'experimental',
  eccentricity: 'eccentric', maximalist: 'eccentric', odd: 'eccentric', unusual: 'eccentric',

  // seeking
  curiosity: 'curious', wondering: 'curious', question: 'inquisitive', questions: 'inquisitive',
  discovery: 'exploratory', discover: 'exploratory', research: 'inquisitive', drift: 'wandering',
  drifting: 'wandering', meander: 'wandering', walk: 'wandering', walking: 'wandering',
  hike: 'adventurous', hiking: 'adventurous', trip: 'wanderlust', vacation: 'wanderlust',
  abroad: 'wanderlust',

  // shadow
  dark: 'moody', darkness: 'moody', shadow: 'moody', shadows: 'moody', dramatic: 'moody',
  drama: 'moody', sullen: 'brooding', ponderous: 'brooding', mystery: 'mysterious',
  secret: 'mysterious', secrets: 'mysterious', cryptic: 'enigmatic', riddle: 'enigmatic',
  ghost: 'haunting', ghostly: 'haunting', ghosts: 'haunting', spooky: 'eerie', creepy: 'eerie',
  halloween: 'eerie', horror: 'eerie', unsettling: 'eerie', foreboding: 'ominous', doom: 'ominous',
  thunderstorm: 'ominous', thunder: 'ominous', storm: 'ominous', stormy: 'ominous',
  victorian: 'gothic', vampire: 'gothic', crypt: 'gothic', detective: 'noir', filmnoir: 'noir',
  blackandwhite: 'monochrome',

  // restraint
  minimalism: 'minimal', minimalist: 'minimal', simple: 'minimal', simplicity: 'minimal',
  bare: 'minimal', plain: 'minimal', scandinavian: 'minimal', japandi: 'minimal', muji: 'minimal',
  neat: 'clean', pure: 'clean', white: 'clean', sharp: 'crisp', clarity: 'crisp', breezy: 'airy',
  open: 'airy', spacious: 'airy', sophisticated: 'refined', classy: 'elegant', chic: 'elegant',
  couture: 'elegant', fashion: 'elegant', subtle: 'understated', muted: 'understated',
  neutral: 'understated', beige: 'understated', greyscale: 'monochrome', grayscale: 'monochrome',
  concrete: 'brutalist',

  // luxe
  luxury: 'luxurious', luxe: 'luxurious', rich: 'luxurious', expensive: 'luxurious',
  gold: 'opulent', baroque: 'opulent', rococo: 'opulent', extravagant: 'opulent',
  indulgent: 'decadent', indulgence: 'decadent', velvet: 'decadent', wine: 'decadent',
  chocolate: 'decadent', glamour: 'glamorous', glam: 'glamorous', hollywood: 'glamorous',
  redcarpet: 'glamorous',

  // land
  earth: 'earthy', terracotta: 'earthy', clay: 'earthy', natural: 'organic', nature: 'organic',
  wood: 'organic', green: 'verdant', forest: 'verdant', jungle: 'verdant', moss: 'verdant',
  woods: 'verdant', trees: 'verdant', plants: 'botanical', plant: 'botanical', garden: 'botanical',
  flowers: 'botanical', floral: 'botanical', greenhouse: 'botanical', leaves: 'botanical',
  ocean: 'oceanic', sea: 'oceanic', waves: 'oceanic', marine: 'oceanic', nautical: 'oceanic',
  water: 'aquatic', underwater: 'aquatic', swimming: 'aquatic', pool: 'aquatic', beach: 'coastal',
  shore: 'coastal', seaside: 'coastal', mountains: 'alpine', mountain: 'alpine', snowy: 'wintry',
  ski: 'alpine', palm: 'tropical', island: 'tropical', sand: 'desert', dunes: 'desert',
  sahara: 'desert', dry: 'arid', drought: 'arid', ice: 'arctic', frozen: 'arctic', polar: 'arctic',
  glacier: 'arctic',

  // season
  autumn: 'autumnal', fall: 'autumnal', october: 'autumnal', harvest: 'autumnal',
  pumpkin: 'autumnal', winter: 'wintry', snow: 'wintry', frost: 'wintry', december: 'wintry',
  blossom: 'vernal', cherryblossom: 'vernal', sakura: 'vernal', summer: 'summery', july: 'summery',
  heat: 'summery',

  // signal
  seventies: 'retro', eighties: 'retro', nineties: 'retro', vaporwave: 'neon', synthwave: 'neon',
  arcade: 'neon', antique: 'vintage', oldschool: 'vintage', classic: 'vintage', sepia: 'vintage',
  film: 'analog', filmgrain: 'analog', polaroid: 'analog', cassette: 'analog', vinyl: 'analog',
  future: 'futuristic', scifi: 'futuristic', spaceage: 'futuristic', cyberpunk: 'cyber',
  hacker: 'cyber', matrix: 'cyber', digital: 'technical', tech: 'technical',
  technology: 'technical', code: 'technical', coding: 'technical', engineering: 'technical',
  machine: 'industrial', factory: 'industrial', warehouse: 'industrial', rust: 'industrial',
  steel: 'industrial', city: 'urban', street: 'urban', metropolis: 'urban', skyline: 'urban',
  subway: 'urban', downtown: 'urban',
})

/**
 * Words that carry no mood on their own. Stripped before matching so
 * "i'm feeling a little bit nostalgic today" still resolves to `nostalgic`.
 */
export const STOP_WORDS = new Set([
  'a',
  'about',
  'all',
  'am',
  'an',
  'and',
  'any',
  'are',
  'as',
  'at',
  'be',
  'been',
  'being',
  'bit',
  'but',
  'by',
  'can',
  'day',
  'do',
  'even',
  'ever',
  'feel',
  'feeling',
  'feels',
  'felt',
  'for',
  'from',
  'get',
  'getting',
  'go',
  'going',
  'had',
  'has',
  'have',
  'i',
  'im',
  'in',
  'is',
  'it',
  'its',
  'just',
  'kinda',
  'like',
  'little',
  'lot',
  'me',
  'mode',
  'month',
  'mood',
  'more',
  'morning',
  'most',
  'much',
  'my',
  'need',
  'not',
  'now',
  'of',
  'on',
  'or',
  'pretty',
  'quite',
  'rather',
  'really',
  'right',
  's',
  'say',
  'so',
  'some',
  'something',
  'sort',
  'style',
  'such',
  't',
  'that',
  'the',
  'their',
  'them',
  'then',
  'these',
  'they',
  'thing',
  'things',
  'this',
  'to',
  'today',
  'tonight',
  'too',
  'type',
  'vibe',
  'vibes',
  'want',
  'was',
  'way',
  'we',
  'week',
  'were',
  'what',
  'when',
  'while',
  'with',
  'would',
  'year',
  'you',
  'your',
])

/**
 * Multi-word phrases checked against the whole query before it is tokenised,
 * so "golden hour" does not get split into two unrelated single-word matches.
 */
export const PHRASE_ALIASES = Object.freeze({
  'golden hour': 'golden',
  'blue hour': 'blue',
  'magic hour': 'golden',
  'film noir': 'noir',
  'black and white': 'monochrome',
  'black white': 'monochrome',
  'deep work': 'focused',
  'road trip': 'wanderlust',
  'new beginning': 'renewed',
  'fresh start': 'renewed',
  'first day': 'renewed',
  'burnt out': 'overwhelmed',
  'burned out': 'overwhelmed',
  'worn out': 'weary',
  'wound up': 'tense',
  'let down': 'sad',
  'fed up': 'angry',
  'over it': 'drained',
  'on edge': 'anxious',
  'at peace': 'peaceful',
  'in love': 'romantic',
  'head over heels': 'romantic',
  'long distance': 'longing',
  'lost in thought': 'introspective',
  'off grid': 'secluded',
  'slow living': 'languid',
  'quiet luxury': 'understated',
  'old money': 'refined',
  'dark academia': 'studious',
  'light academia': 'studious',
  'cottage core': 'pastoral',
  cottagecore: 'pastoral',
  'mid century': 'retro',
  'art deco': 'opulent',
  'art nouveau': 'elegant',
  'sci fi': 'futuristic',
  'science fiction': 'futuristic',
  'late night': 'noir',
  'early morning': 'fresh',
  'rainy day': 'melancholy',
  'sunny day': 'sunny',
  'snow day': 'wintry',
  'first snow': 'wintry',
  'cherry blossom': 'vernal',
  'northern lights': 'awed',
  'milky way': 'cosmic',
  'deep sea': 'oceanic',
  'open road': 'wanderlust',
  'big city': 'urban',
  'small town': 'pastoral',
})
